Feature/quantization/langchain——can run local get the same result of big model
ymcui/Chinese-LLaMA-Alpaca pull request #396
Opened 2023-05-20 16:14 UTC by HardSoft2023

1、simplfy the langchai_qa.py demo code so that it can run locally
<img src="https://wechatlongterm.oss-cn-beijing.aliyuncs.com/ChinesePR.png" alt="ChinesePR" style="zoom:200%;" />

2、`python langchain_qa_quantization.py --model_path path/to/chinese_alpaca_plus_pth/7B/ggml-model-q4_0.bin --file_path doc.txt`

2023-05-24 03:42 UTC, airaria requested changes

2023-05-24 03:42 UTC, airaria commented on scripts/langchain_demo/langchain_qa.py
> +from langchain.llms import LlamaCpp
Rather than completely removing HuggingFacePipeline, should add an option for the users to choice HuggingFacePipeline or llama.cpp

2023-05-24 03:42 UTC, airaria commented on scripts/langchain_demo/langchain_qa_quantization.md
> +
It looks to be incomplete. Still under construction?

2023-05-24 03:42 UTC, airaria commented on scripts/langchain_demo/langchain_qa_quantization.py
> +            print('\n* 本次检索结束 *\n')
Nice example. But it is a bit overlapped with the existing examples.
To ensure clarity and avoid redundancy, we will not include the example at the moment until we reorganize our scripts and examples.

2023-06-13 03:01 UTC, ymcui commented
Thank you for your contributions to our repo. 
As we haven't received your revisions, I will temporarily convert this PR in draft status.
Feel free to change the status when you are ready for review.

2023-06-28 00:09 UTC, closed without merging