Adding OPENAI API Demo using FastAPI
ymcui/Chinese-LLaMA-Alpaca pull request #530
Opened 2023-06-07 15:13 UTC by sunyuhan19981208

## Description
This pull request adds a demo of the OPENAI API using FastAPI. The demo includes support for three APIs: completions, chat/completions and embeddings.
## Changes Made
 - Created a new directory named api_server_demo in the project root.
 - Added a new file openai_api_server.py and openai_api_protocol.py in the api_server_demo directory containing the implementation of the API demo.
 - Implemented three API endpoints: /v1/completions, /v1/chat/completions, and /v1/embeddings.
 - Utilized FastAPI for creating the API server and handling HTTP requests.
 - Added necessary api reference document in the README.md file.
## Usage

Use the command below to deploy the server.

``` shell
python scripts/openai_server_demo/openai_api_server.py --base_model /path/to/base_model --lora_model /path/to/lora_model --gpus 0,1
```

## Test APIs

completions:

``` shell
curl http://localhost:19327/v1/completions \
  -H "Content-Type: application/json" \
  -d '{   
    "prompt": "告诉我中国的首都在哪里"
  }'
```

chat:

``` shell
curl http://localhost:19327/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{   
    "messages": [
      {"role": "user","message": "给我讲一些有关杭州的故事吧"}
    ],
    "repetition_penalty": 1.0
  }'
```

embeddings:

``` shell
curl http://localhost:19327/v1/embeddings \
  -H "Content-Type: application/json" \
  -d '{
    "input": "今天天气真不错"
  }'
```

2023-06-14 02:25 UTC, 1anglesmith1 commented
你好，请问一下，我按照教程将中文版的llama模型在Windows本地部署了，但是怎么样才能去调用这个本地模型的api或者通过其他方法定义问题然后模型推理返回一个输出呢？

2023-06-14 07:05 UTC, sunyuhan19981208 commented
> 你好，请问一下，我按照教程将中文版的llama模型在Windows本地部署了，但是怎么样才能去调用这个本地模型的api或者通过其他方法定义问题然后模型推理返回一个输出呢？

使用Python的requests库可以发送HTTP请求。以下是将curl命令转换为使用requests库发送POST请求的示例代码：

```python

import requests
import json

url = 'http://localhost:19327/v1/chat/completions'
headers = {
    'Content-Type': 'application/json'
}

data = {
    'messages': [
        {'role': 'user', 'message': '给我讲一些有关杭州的故事吧'}
    ],
    'repetition_penalty': 1.0
}

response = requests.post(url, headers=headers, data=json.dumps(data))

print(response.json())
```
确保已安装requests库。可以使用以下命令通过pip安装：

``` shell
pip install requests
```
请注意，要成功执行此代码，您的本地服务器必须运行，并且在 http://localhost:19327 上接受POST请求。

2023-06-14 09:05 UTC, 1anglesmith1 commented
> > 你好，请问一下，我按照教程将中文版的llama模型在Windows本地部署了，但是怎么样才能去调用这个本地模型的api或者通过其他方法定义问题然后模型推理返回一个输出呢？
> 
> 使用Python的requests库可以发送HTTP请求。以下是将curl命令转换为使用requests库发送POST请求的示例代码：
> 
> ```python
> import requests
> import json
> 
> url = 'http://localhost:19327/v1/chat/completions'
> headers = {
>     'Content-Type': 'application/json'
> }
> 
> data = {
>     'messages': [
>         {'role': 'user', 'message': '给我讲一些有关杭州的故事吧'}
>     ],
>     'repetition_penalty': 1.0
> }
> 
> response = requests.post(url, headers=headers, data=json.dumps(data))
> 
> print(response.json())
> ```
> 
> 确保已安装requests库。可以使用以下命令通过pip安装：
> 
> ```shell
> pip install requests
> ```
> 
> 请注意，要成功执行此代码，您的本地服务器必须运行，并且在 http://localhost:19327 上接受POST请求。

你好，非常感谢你的回答，但是我在启动本地服务器的时候，选用13b的模型最后报错说gpu显存不够，我的gpu显存是24G，在powershell上可以通过量化后的模型进行推理，但是按照您的方法要将两个模型全部加载进去就会有问题。请问有方法可以通过量化后的13b模型去做一个api的交互吗？或者减少显存的消耗

2023-06-14 10:18 UTC, sunyuhan19981208 commented
@1anglesmith1 可以在启动选项中添加`--load_in_8bit`

2023-06-15 02:01 UTC, 1anglesmith1 commented
> --load_in_8bit

我怎么加的都是报错没这个参数：usage: openai_api_server.py [-h] --base_model BASE_MODEL [--lora_model LORA_MODEL] [--tokenizer_path TOKENIZER_PATH]
                            [--gpus GPUS] [--load_in_8bit] [--only_cpu]
openai_api_server.py: error: unrecognized arguments: --load_in_4bit
这个 --load_in_4bit应该加在启动项哪里呢

2023-06-15 02:12 UTC, sunyuhan19981208 commented
@1anglesmith1 没有4bit，只有8bit

2023-06-15 02:12 UTC, 1anglesmith1 commented
> @1anglesmith1没有4bit，只有8bit

python scripts/openai_server_demo/openai_api_server.py --base_model /path/to/base_model --lora_model /path/to/lora_model --gpus 0,1 --load_in_8bit 是这样吗？

2023-06-15 02:13 UTC, sunyuhan19981208 commented
@1anglesmith1 是的，你一张卡就--gpus 0

2023-06-15 02:31 UTC, ymcui commented
Thank you for your continuous contributions. 
After a quick scanning, the proposed PR might be a valuable addition to our project.
In the meantime, we are sorry for the delay in reviewing this PR as we are packed with other work to do.
We will review this PR asap and thanks again for your understanding.

2023-06-15 02:48 UTC, sunyuhan19981208 commented
> @sunyuhan19981208 你好，感谢你的贡献。我在跑你的代码 `openai_api_server.py` 时，发现一个问题：在调用api服务计算一句话的embeddings时，抛出异常：
> 
> ```shell
> raise ValueError(
> ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.
> ```
> 
> 解决措施：是不是需要在 161 行的下面，插入一行代码：
> 
> ```python
> tokenizer.add_special_tokens({'pad_token': '[PAD]'})
> ```
> 
> 我插入一行后，再次运行服务，就没有报错了。

好的，感谢您的测试，我自己测试的时候没发现这个问题，我今天下班去看一下啥原因

2023-06-15 13:57 UTC, sunyuhan19981208 commented
@TommyTang930 
我这个加载进来默认就是有pad_token的，我估计你那个模型合完应该是没有tokenizer，不过也很感谢您发现了这一点，我加一个判断
``` python
(Pdb) p tokenizer
LlamaTokenizer(name_or_path='/home/sunyuhan/syh/sunyuhan/zju/chinese-alpaca-plus-7b', vocab_size=49954, model_max_length=1000000000000000019884624838656, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'pad_token': '[PAD]'}, clean_up_tokenization_spaces=False)
```

2023-06-19 07:03 UTC, airaria commented on scripts/openai_server_demo/openai_api_server.py
> +    return prompt
Alpaca models have not been trained with a different prompt template for multi-turn conversations.
While in our training scheme, the multi-turn conversation is formatted as follows:

```
Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
{instruction}

### Response: {response}

### Instruction:
{instruction}

### Response: {response}

...
```

However, it is possible that the format you used above is more appropriate for multi-turn conversations in inference.
Can you please compare the formats and determine which option is superior? If necessary, please modify the code accordingly.

2023-06-19 07:05 UTC, airaria requested changes
It may need to modify `generate_chat_prompt`

2023-06-19 07:24 UTC, sunyuhan19981208 commented on scripts/openai_server_demo/openai_api_server.py
> +    return prompt
I will modify it tonight, thanks a lot for your code review!!!!

2023-06-20 01:15 UTC, airaria approved these changes

2023-06-20 01:49 UTC, ymcui approved these changes

2023-06-20 02:29 UTC, merged